In [24]:
############ Excercise 1 ##########
# 1. Import the numpy package under the name `np` 


import numpy as np


In [25]:
############ Excercise 2 ##########
# 2. Create a null vector of size 10

n = 10

null_v = np.zeros(n)
print(null_v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [26]:
############ Excercise 3 ##########
# 3. Create a null vector of size 10 but the fifth value which is 1 
n = 10

null_v5 = np.zeros(n)
null_v5[-1] = 5
print(null_v5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]


In [28]:
#### 4. Create a vector with values ranging from 10 to 49
v1 = np.arange(10, 50)
print(v1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [37]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8
v2 = np.arange(0, 9)
v3 = v2.reshape((3, 3))
print(v3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0]
n = [1,2,0,0,4,0]
non_z = np.nonzero(n)
print(non_z)

(array([0, 1, 4]),)


In [40]:
#### 7. Create a 3x3 identity matrix 
i = np.eye(3, 3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
#### 8. Create a 3x3x3 array with random values 
third = np.random.random((3,3,3))
print(third)

[[[0.41699453 0.96357507 0.89433379]
  [0.60791462 0.41601848 0.24542332]
  [0.81130221 0.37427589 0.99038385]]

 [[0.94166693 0.76425477 0.26168617]
  [0.04155367 0.6942567  0.47522049]
  [0.45435532 0.01728234 0.19049787]]

 [[0.4287936  0.10600288 0.78301268]
  [0.18208389 0.7534409  0.37506058]
  [0.66197651 0.65830914 0.91457529]]]


In [53]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
ten = np.random.random((10,10))
Minimal = ten.min()
Maximal = ten.max()

print(Minimal)
print(Maximal)

0.029364104515817502
0.9819709628771961


In [51]:
#### 10. Create a random vector of size 30 and find the mean value
vs = np.random.random((1,30))
Mean_vs = vs.mean()
print(Mean_vs)

0.5309248173969215


In [65]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
cinco = np.diag(np.arange(1,5), k=-1)
print(cinco)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [70]:
#### 12. Normalize a 5x5 random matrix
# Hint: (x -mean)/std` 
#--> To normalize a matrix means to scale 
# the values such that that the range of the row or column 
# values is between 0 and 1.

d = np.random.random((5, 5))
print(d)


[[0.30547553 0.34913816 0.56339146 0.43677781 0.24049891]
 [0.95415332 0.65677427 0.14971952 0.81278643 0.43211474]
 [0.23240818 0.95917392 0.57204077 0.91721757 0.5059969 ]
 [0.92924541 0.93802386 0.25061424 0.72649278 0.97519858]
 [0.89578798 0.3651911  0.60801452 0.34358309 0.22521943]]


In [76]:
mean_d = np.mean(d)
stdev_d = np.std(d)

normalized_data = (d-mean_d)/stdev_d
print(normalized_data)

[[-0.96839283 -0.81081368 -0.03757015 -0.4945208  -1.20289448]
 [ 1.3726956   0.29944991 -1.53051872  0.86250024 -0.51134989]
 [-1.23209404  1.39081503 -0.00635465  1.2393939  -0.24470803]
 [ 1.28280257  1.31448413 -1.16638808  0.5510651   1.44864827]
 [ 1.16205418 -0.75287837  0.1234752  -0.83086202 -1.25803837]]


In [80]:
#### 13. How to find common values between two arrays?
# np.intersect1d
common = np.intersect1d([1,4,5,7,8],[7,3,4,1])
print(common)

[1 4 7]


In [90]:
#### 14. Create a random vector of size 10 and sort it
# sort
r = np.rand((1,10))
print(r)

AttributeError: module 'numpy' has no attribute 'rand'