In [2]:
############ Excercise 1 ##########
# 1. Import the numpy package under the name `np` 


import numpy as np


In [3]:
############ Excercise 2 ##########
# 2. Create a null vector of size 10

n = 10

null_v = np.zeros(n)
print(null_v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
############ Excercise 3 ##########
# 3. Create a null vector of size 10 but the fifth value which is 1 
n = 10

null_v5 = np.zeros(n)
null_v5[-1] = 5
print(null_v5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]


In [5]:
#### 4. Create a vector with values ranging from 10 to 49
v1 = np.arange(10, 50)
print(v1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8
v2 = np.arange(0, 9)
v3 = v2.reshape((3, 3))
print(v3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0]
n = [1,2,0,0,4,0]
non_z = np.nonzero(n)
print(non_z)

(array([0, 1, 4]),)


In [8]:
#### 7. Create a 3x3 identity matrix 
i = np.eye(3, 3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#### 8. Create a 3x3x3 array with random values 
third = np.random.random((3,3,3))
print(third)

[[[0.63943405 0.77257928 0.39391496]
  [0.40385677 0.93743569 0.74590573]
  [0.96043003 0.04938649 0.69403036]]

 [[0.95496258 0.06808728 0.94833441]
  [0.49515251 0.41365759 0.66649236]
  [0.47291627 0.4016004  0.70034039]]

 [[0.63489086 0.86347495 0.14806444]
  [0.91789417 0.19585497 0.99792509]
  [0.09420703 0.14588209 0.37344785]]]


In [10]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
ten = np.random.random((10,10))
Minimal = ten.min()
Maximal = ten.max()

print(Minimal)
print(Maximal)

0.0058950151804688655
0.9912247556951952


In [11]:
#### 10. Create a random vector of size 30 and find the mean value
vs = np.random.random((1,30))
Mean_vs = vs.mean()
print(Mean_vs)

0.4450282035820257


In [12]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
cinco = np.diag(np.arange(1,5), k=-1)
print(cinco)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [13]:
#### 12. Normalize a 5x5 random matrix
# Hint: (x -mean)/std` 
#--> To normalize a matrix means to scale 
# the values such that that the range of the row or column 
# values is between 0 and 1.

d = np.random.random((5, 5))
print(d)


[[0.58122951 0.76937937 0.25116433 0.6226648  0.64281543]
 [0.53350373 0.42744043 0.84630784 0.01557735 0.90826398]
 [0.14442552 0.15766924 0.41843912 0.27911627 0.79679024]
 [0.83556703 0.40752715 0.52979499 0.840454   0.26434994]
 [0.19413143 0.3814108  0.67751052 0.01156706 0.33971144]]


In [14]:
mean_d = np.mean(d)
stdev_d = np.std(d)

normalized_data = (d-mean_d)/stdev_d
print(normalized_data)

[[ 0.39866157  1.10523845 -0.8408633   0.55426742  0.62994097]
 [ 0.21943245 -0.17887706  1.39413518 -1.72558525  1.6268049 ]
 [-1.2417096  -1.1919742  -0.21268053 -0.73589272  1.20817709]
 [ 1.3537992  -0.25365925  0.20550466  1.3721517  -0.79134614]
 [-1.05504432 -0.35173645  0.76023471 -1.74064549 -0.50833398]]


In [15]:
#### 13. How to find common values between two arrays?
# np.intersect1d
common = np.intersect1d([1,4,5,7,8],[7,3,4,1])
print(common)

[1 4 7]


In [16]:
#### 14. Create a random vector of size 10 and sort it
# sort
r = np.random.randint(low=1, high=11, size=10)
print(r)
r_sorted = np.sort(r)
print(r_sorted)

[10  4  9  5  6  8  2  1  6  3]
[ 1  2  3  4  5  6  6  8  9 10]


In [17]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 
#argmax

s = np.random.random(10)
print(s)
s[s.argmax()]=0
s


[0.85752051 0.24259638 0.29934493 0.82112491 0.13740201 0.98995668
 0.93561667 0.63996238 0.40253567 0.73099246]


array([0.85752051, 0.24259638, 0.29934493, 0.82112491, 0.13740201,
       0.        , 0.93561667, 0.63996238, 0.40253567, 0.73099246])

In [18]:
#### 16. Subtract the mean of each row of a matrix
# `hint: mean(axis=,keepdims=)`

m = np.random.random((4,4))


m -= np.mean(m, axis=1, keepdims=True)
print(m)

[[ 0.48665921 -0.2910796  -0.06549792 -0.1300817 ]
 [-0.06999902  0.14527301  0.02592699 -0.10120098]
 [ 0.30338136 -0.33536261  0.15829929 -0.12631805]
 [ 0.14079794 -0.17066321 -0.2771656   0.30703086]]


In [19]:
#### 17. How to get the n largest values of an array
# hint: np.argsort | np.argpartition`
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z)

u = np.argsort(Z)[-n:]
largest_values = Z[u]
print(largest_values)

[1166 6262 7313 ...  132 7061 4403]
[9995 9996 9997 9998 9999]


In [20]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`

x = np.random.randint(low=1, high=11, size=(5,3))
print(x)


[[10  9  8]
 [ 9  1  9]
 [ 2  2  3]
 [ 3  3  4]
 [ 5  1  5]]


In [121]:
x_power = np.where(x > 4, x**2, x)
print(x_power)

[[ 36  81  49]
 [ 36  36  81]
 [  4  49   2]
 [100  36  25]
 [  1  49  36]]
